language: python
python:
- 2.7
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: glow-mdsol
  password:
    secure: oskT5IMVSldMDgM40Utq9jgB5SV0h/lOMR5RLLcDFP0Ln3tbzlKM0gHnPdgnsVvPxSDWyCoNfXh2GRuPH2eYesKZ1Yt/l3XClvdXQCODQq4MjegeN1yy8YqdR0Xld83/fxPQLzpmP1aF5eouWXHb8zG7G3GX6kyunpadhSjSudw=
  on:
    tags: true
    python: '3.6'
  distributions: sdist
